service: sehwan-${self:custom.regionAbbr.${self:provider.region}}-edge-provisioner

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  stackName: ${self:service}-${self:provider.stage}
  ArtifactBucket: ${self:service}-${opt:stage}-artifact

custom:
  defaultStage: dev
  regionAbbr:
    ap-northeast-2: an2
  sehwan: sehwan-${self:custom.regionAbbr.${self:provider.region}}


resources:
  Description: "Provisioner Stack"
  Resources:
    ArtifactBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.ArtifactBucket}
  Outputs:
    ArtifactBucketRef:
      Value: { Ref: ArtifactBucket }
      Export:
        Name: ArtifactBucketRef
