service: sehwan-${self:custom.regionAbbr.${self:provider.region}}-edge

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, self:custom.defaultStage}
  stackName: ${self:service}-${self:provider.stage}
  resourcesStackName: ${self:custom.sehwan}-resources-${self:provider.stage}
  #profile: ${self:custom.profiles.${self:provider.stage}}
  runtimeArtifactBucket: ${self:service}-${opt:stage}-runtime-artifact
  rawdataBucket: ${self:service}-${opt:stage}-rawdata
  versionFunctions: true

package:
  individually: true

custom:
  defaultStage: dev
  regionAbbr:
    ap-northeast-2: an2
  sehwan: sehwan-${self:custom.regionAbbr.${self:provider.region}}
  pythonRequirements:
    dockerizePip: true
    useDownloadCache: false
    useStaticCache: false
    noDeploy: [] # For including boto3, botocore explicitly into greengrass 

plugins:
  - serverless-python-requirements
  - serverless-aws-alias
resources:
  Description: "Edge Resource Stack"
  Resources:
    RuntimeArtifactBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.runtimeArtifactBucket}
    RawdataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.rawdataBucket}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
              MaxAge: 3000
  Outputs:
    RuntimeArtifactBucketRef:
      Value: { Ref: RuntimeArtifactBucket }
      Export:
        Name: RuntimeArtifactBucketRef
    RawdataBucketRef:
      Value: { Ref: RawdataBucket }
      Export:
        Name: RawdataBucketRef

functions:
  sehwanTest:
    module: sehwanTest
    handler: main.handler
    name: ${self:provider.stackName}-sehwanTest
 