service: batch-lambda-dev

provider:
  name: aws
  runtime: python3.7
  memorySiz: 1024
  timeout: 900 # seconds
  stage: ${opt:stage, self:custom.defaultStage}
  stackName: ${self:service}-${self:provider.stage}
  versionFunctions: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
        - "dynamodb:*"
        - "lambda:*"
        - "s3:*"
      Resource: "*" 
  environment:
    RAW_BUCKET: "sehwan-an2-edge-dev-rawdata"
    TRIGGERD_LAMDA: ${self:service}-stat-get-trigger
    HOUR_STAT_TABLE: 'dynamodb-resources-Hour-stat'
    DAY_STAT_TABLE: 'dynamodb-resources-Day-stat'
    MONTH_STAT_TABLE: 'dynamodb-resources-Month-stat'


package:
  individually: true
  exclude:
    - node_modules/**

plugins:
  - serverless-python-requirements

custom:
  defaultStage: dev
  regionAbbr:
    ap-northeast-2: an2
  pythonRequirements:
    dockerizePip: true
    useDownloadCache: false 
    useStaticCache: false

resources:
  Description: "batch lambdas"

functions:
  lmd_trigger:
    handler: lmd_trigger.handler
    name: ${self:service}-stat-trigger
    events:
      - schedule: cron(0 * * * ? *) # every 60 mins
  lmd_get_trigger:
    handler: lmd_get_trigger.handler
    name: ${self:service}-stat-get-trigger